#!/bin/bash
set -e

./build/bas wordle/main.asm wordle/words.asm wordle/strings.asm stdlib/term.asm stdlib/string.asm stdlib/keyboard.asm stdlib/keymap_fr_be.asm stdlib/keymap_fr_be_shift.asm stdlib/keymap_fr_be_altgr.asm stdlib/keycodes.asm stdlib/rand.asm -f header -o ../raccoon/bitstream_loader/src/rom.h
cd ../raccoon
uflake-tools make
./upload_ryz.sh