title_str:      .str "  RPN Calculator"
prompt_str:     .str ">           "
add_str:        .str "+"
sub_str:        .str "-"
mul_str:        .str "*"
div_str:        .str "/"
modulo_str:     .str "%"
drop_str:       .str "d"
result_str:     .str "result"